# Generated by Django 2.2 on 2019-04-22 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battleroom',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('bname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('pname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('battleroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='microservices.Battleroom')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microservices.Player')),
            ],
            options={
                'unique_together': {('battleroom', 'player')},
            },
        ),
    ]
